# Configuración AWS
aws_region: "us-east-1"
project_name: "cc-contenedores"
account_id: "712395067123"

# EKS Configuration
eks_cluster_name: "{{ project_name }}-cluster"
eks_version: "1.28"
eks_nodegroup_name: "{{ project_name }}-nodes"

# Instancias EKS
eks_instance_type: "t3.micro"
eks_desired_size: 1
eks_min_size: 1
eks_max_size: 3

# Networking
vpc_cidr: "10.0.0.0/16"
# CIDRs para las subnets en diferentes AZs
subnet_1_cidr: "10.0.1.0/24"
subnet_2_cidr: "10.0.2.0/24"
# También puedes definir las AZs si quieres
availability_zone_1: "us-east-1a"
availability_zone_2: "us-east-1b"

# IAM Roles (debes crear estos roles manualmente primero)
eks_cluster_role_arn: "arn:aws:iam::{{ account_id }}:role/eks-cluster-role"
eks_nodegroup_role_arn: "arn:aws:iam::{{ account_id }}:role/eks-nodegroup-role"

# Key Pair
key_name: "mi-keypair"