---
- name: ðŸš€ Despliegue Completo - CC Contenedores en EKS
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/all.yaml
    - group_vars/aws.yaml

  tasks:
    - name: ðŸŽ¯ Ejecutar despliegue completo
      include_tasks: site.yaml