all:
  vars:
    ansible_python_interpreter: /home/egrm23/miniconda3/bin/python3.13
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  hosts:
    localhost:
      ansible_connection: local